### ISSUE TITLE
Add Bancor v2

### ISSUE THREAD

**Issue by tiagofilipenunes** [dmihal/crypto-fees#21]
Hey David, I thought I'd help by updating Bancor to v2. I've added a description based on the Uniswap and Balancer descriptions to be consistent, and used the fetcher in the same way as AAVE, as there was only a JSON to parse. 

I hope this is okay or at least helps you.

**Comment by dmihal** [comment]
Hey, thanks for creating this PR.

While we're updating the Bancor adapter, I'd love to actually fully update Bancor to V2, which would require fetching data by dates. Are you involved with the Bancor API at all? Do you know if it's possible to query this data by date?

**Comment by tiagofilipenunes** [comment]
Hey David, I've asked the Bancor team about this - their API is currently being updated and doesn't support querying data by date yet. Can it be partially updated for now? Once the feature is available, I'll communicate here again if you want. Thanks!

**Comment by dmihal** [comment]
Awesome, I messaged with their team too.

Went ahead and merged your PR, thanks for your contribution!
